export const ProductsData = [
	{
		id: 1,
		// sku: ,
		title: "T-Shirt 1",
		quantity: 1,
		describtion: "TT1",
		availableSizes: ["X", "L", "Xl"],
		price: 31.8,
		isFreeShopping: true,
	},
	{
		id: 2,
		// sku: ,
		title: "Skirt",
		quantity: 1,
		describtion: "SSSSS",
		availableSizes: ["X", "L", "XXL"],
		price: 27.5,
		isFreeShopping: true,
	},
	{
		id: 3,
		// sku: ,
		title: "Shoes",
		quantity: 3,
		describtion: "SSSSS",
		availableSizes: ["X", "L", "XL"],
		price: 31,
		isFreeShopping: false,
	},
	{
		id: 4,
		// sku: ,
		title: "Bag 2",
		quantity: 2,
		describtion: "BBBB2",
		availableSizes: ["S", "L"],
		price: 12.9,
		isFreeShopping: true,
	},
	{
		id: 5,
		// sku: ,
		title: "Bag 1",
		quantity: 4,
		describtion: "BBBB1",
		availableSizes: ["S", "M"],
		price: 15.7,
		isFreeShopping: false,
	},
	{
		id: 6,
		// sku: ,
		title: "Socks",
		quantity: 6,
		describtion: "SSSSSS",
		availableSizes: ["XL"],
		price: 10,
		isFreeShopping: false,
	},
	{
		id: 7,
		// sku: ,
		title: "T-Shirt 2",
		quantity: 1,
		describtion: "TT2",
		availableSizes: ["XXL"],
		price: 25.3,
		isFreeShopping: true,
	},
	{
		id: 8,
		// sku: ,
		title: "Jean",
		quantity: 5,
		describtion: "JJJJJJ",
		availableSizes: ["S"],
		price: 20.6,
		isFreeShopping: false,
	},

]